version: '3.8'

services:
  postgres-dev:
    image: postgres:17.0-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lemme-api-dev-db
    ports:
      - "5433:5432"

  postgres-test:
    image: postgres:17.0-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lemme-api-test-db
    ports:
      - "5434:5432"
